databases:
  - name: postpartum_db
    databaseName: postpartum_health
    user: postgres
    plan: free

services:
  - type: web
    name: postpartum-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn postpartum_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postpartum_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false