# Generated by Django 5.1.7 on 2025-04-13 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired'), ('unknown', 'Unknown')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('name_last', models.CharField(default='Unknown', max_length=30)),
                ('name_first', models.CharField(default='Unknown', max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=30)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('final', 'Final'), ('update', 'Update'), ('unknown', 'Unknown')], default='update', max_length=30)),
                ('category', models.CharField(choices=[('vital-signs', 'Vital Signs')], default='vital-signs', max_length=50)),
                ('code', models.CharField(choices=[('21522001', 'Abdominal Pain'), ('386661006', 'Bleeding'), ('25064002', 'Headache'), ('10601006', 'Body Ache'), ('229373006', 'Leg Pain'), ('29857009', 'Chest Pain'), ('75879001', 'Breast Pain'), ('49650001', 'Discomfort Urinating'), ('35489007', 'Sadness'), ('48694002', 'Anxiety')], max_length=50)),
                ('code_display', models.CharField(max_length=100)),
                ('value_quantity', models.FloatField(default='0.0')),
                ('value_unit', models.CharField(default='1-10', max_length=30)),
                ('effective_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='postpartum_api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('amended', 'Amended'), ('entered-in-error', 'Entered in error'), ('stopped', 'Stopped')], max_length=20)),
                ('authored', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='postpartum_api.patient')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='postpartum_api.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postpartum_api.observation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postpartum_api.patient')),
                ('questionnaire_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postpartum_api.questionnaireresponse')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('answer_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_integer', models.IntegerField(blank=True, null=True)),
                ('answer_string', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='postpartum_api.questionnaireresponse')),
            ],
        ),
    ]
